parameters:
#    cooperativa_admin.example.class: Cooperativa\Bundle\AdminBundle\Example

services:
#    cooperativa_admin.example:
#        class: %cooperativa_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
