parameters:
#    cooperativa_admin.example.class: Cooperativa\Bundle\AdminBundle\Example

services:
  sonata.admin.produto:
    class: Cooperativa\Bundle\AdminBundle\Admin\ProdutoAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: Produtos, label: Produtos }
    arguments: [null, Cooperativa\Bundle\AdminBundle\Entity\Produto, null]
    
  sonata admin.contato:
    class: Cooperativa\Bundle\AdminBundle\Admin\ContatoAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: contato, label: Contato }
    arguments: [null, Cooperativa\Bundle\AdminBundle\Entity\Contato, null]

  sonata.admin.produtor:
    class: Cooperativa\Bundle\AdminBundle\Admin\ProdutorAdmin
    tags: 
      - { name: sonata.admin, manager_type: orm, group: Cadastros, label: Produtores }
    arguments: [null, Cooperativa\Bundle\AdminBundle\Entity\Produtor, null]

  sonata.admin.entidade:
    class: Cooperativa\Bundle\AdminBundle\Admin\EntidadeAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: Cadastros, label: Entidades }
    arguments: [null, Cooperativa\Bundle\AdminBundle\Entity\Entidade, null]

  sonata.admin.estoque:
    class: Cooperativa\Bundle\AdminBundle\Admin\EstoqueAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: Produtos, label: Estoque }
    arguments: [null, Cooperativa\Bundle\AdminBundle\Entity\Estoque, null]

  sonata.admin.pagamento:
    class: Cooperativa\Bundle\AdminBundle\Admin\PagamentoAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: Operações, label: Pagamento }
    arguments: [null, Cooperativa\Bundle\AdminBundle\Entity\Pagamento, null]