parameters:
#    cooperativa_admin.example.class: Cooperativa\Bundle\AdminBundle\Example

services:
  sonata.admin.produto:
    class: Cooperativa\Bundle\AdminBundle\Admin\ProdutoAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: produtos, label: Produtos }
    arguments: [null, Cooperativa\Bundle\AdminBundle\Entity\Produto, null]