parameters:
#    cooperativa_admin.example.class: Cooperativa\Bundle\AdminBundle\Example

services:
  sonata.admin.produto:
    class: Cooperativa\Bundle\AdminBundle\Admin\ProdutoAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: Produtos, label: Produtos }
    arguments: [null, Cooperativa\Bundle\AdminBundle\Entity\Produto, null]

  sonata admin.contato:
    class: Cooperativa\Bundle\AdminBundle\Admin\ContatoAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: Contato, label: Contato }
    arguments: [null, Cooperativa\Bundle\AdminBundle\Entity\Contato, null]

  sonata.admin.produtor:
    class: Cooperativa\Bundle\AdminBundle\Admin\ProdutorAdmin
    tags: 
      - { name: sonata.admin, manager_type: orm, group: Cadastros, label: Produtores }
    arguments: [null, Cooperativa\Bundle\AdminBundle\Entity\Produtor, null]

  sonata.admin.entidade:
    class: Cooperativa\Bundle\AdminBundle\Admin\EntidadeAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: Cadastros, label: Entidades }
    arguments: [null, Cooperativa\Bundle\AdminBundle\Entity\Entidade, null]

  sonata.admin.estoque:
    class: Cooperativa\Bundle\AdminBundle\Admin\EstoqueAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: Produtos, label: Estoque }
    arguments: [null, Cooperativa\Bundle\AdminBundle\Entity\Estoque, null]

  sonata.admin.pagamento:
    class: Cooperativa\Bundle\AdminBundle\Admin\PagamentoAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: Operações, label: Pagamento }
    arguments: [null, Cooperativa\Bundle\AdminBundle\Entity\Pagamento, null]

  sonata.admin.produtor_contrato:
    class: Cooperativa\Bundle\AdminBundle\Admin\ProdutorContratoAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: Operações, label: Contrato de produtor }
    arguments: [null, Cooperativa\Bundle\AdminBundle\Entity\ProdutorContrato, null]

  sonata.admin.entidade_contrato:
    class: Cooperativa\Bundle\AdminBundle\Admin\ContratoEntidadeAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: Operações, label: Contrato de entidade }
    arguments: [null, Cooperativa\Bundle\AdminBundle\Entity\ContratoEntidade, null]

  validator.unique.contrato.entidade.ativo:
    class: Cooperativa\Bundle\AdminBundle\Validator\Constraints\UnicoContratoEntidadeAtivoValidator
    tags: 
      - { name: validator.constraint_validator, alias: unico_contrato_entidade_ativo }
    arguments: [@doctrine]

  validator.unique.contrato.produtor.ativo:
    class: Cooperativa\Bundle\AdminBundle\Validator\Constraints\UnicoContratoProdutorAtivoValidator
    tags: 
      - { name: validator.constraint_validator, alias: unico_contrato_produtor_ativo }
    arguments: [@doctrine]

  validator.percentual.entidade:
    class: Cooperativa\Bundle\AdminBundle\Validator\Constraints\PercentualEntidadeValidator
    arguments: [@doctrine]
    tags:
     - { name: validator.constraint_validator, alias: entidade_percentual }